In [2]:
import numpy as np
a = np.random.randn(5) # 这样创建的是rank 1,
print(a)

[-0.07069467 -0.91578993 -1.7569514   0.42207782  0.46283739]


In [6]:
print(a.shape) # 这是rank 1 array, 

(5,)


In [7]:
print(a.T)

[-0.07069467 -0.91578993 -1.7569514   0.42207782  0.46283739]


In [9]:
print(np.dot(a, a.T))

4.32291527062345


尽量不要使用rank 1 的array


In [19]:
b = np.random.randn(5,1) # 这样创建的是真正的矩阵
print(b)

[[ 0.42239594]
 [ 0.20457427]
 [-0.43394469]
 [ 2.2108712 ]
 [-1.12159142]]


In [25]:
print(b.shape)
assert(a.shape == (5,1))

(5, 1)


In [21]:
print(b.T)

[[ 0.42239594  0.20457427 -0.43394469  2.2108712  -1.12159142]]


In [22]:
print(np.dot(b, b.T))

[[ 0.17841833  0.08641134 -0.18329648  0.93386302 -0.47375567]
 [ 0.08641134  0.04185063 -0.08877392  0.45228736 -0.22944874]
 [-0.18329648 -0.08877392  0.18830799 -0.95939581  0.48670864]
 [ 0.93386302  0.45228736 -0.95939581  4.88795146 -2.47969417]
 [-0.47375567 -0.22944874  0.48670864 -2.47969417  1.25796732]]
