In [3]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [33]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

start1 = time.time()
c = np.dot(a,b)
end1 = time.time()
print("Vectorization version:", str(1000*(end1 - start1)) ,"ms")

c = 0
start2 = time.time()
for i in range(1000000):
    c += a[i] * b[i]
end2 = time.time()
print("For loop version: ", str(1000*(end2 - start2)), "ms")

Vectorization version: 0.8270740509033203 ms
For loop version:  404.0536880493164 ms


for loop 500倍

In [37]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [38]:
a = np.array([1,2,3,4])
1/a

array([1.        , 0.5       , 0.33333333, 0.25      ])